#!/usr/bin/php
<?php

$nebsites_path = 'nebsites.json';
	
$nebsites_configuration = new class {};

if (
	is_file($nebsites_path)
	&& is_readable($nebsites_path)
) {

	$nebsites_configuration = json_decode(file_get_contents($nebsites_path));
}

$output = [];
$return = 0;
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);
unset($output);

$files = [];
exec(
	'git diff-index --cached --name-status '
	. (
		$return === 0
		? 'HEAD'
		: '4b825dc642cb6eb9a060e54bf8d69288fbee4904'
	)
	. ' | egrep \'^(A|M)\' | awk \'{print $2;}\'',
	$files
);

$output = [];
$return = 0;
$returns = [];

$phpstan_path =
	'vendor'
	. DIRECTORY_SEPARATOR
	. 'bin'
	. DIRECTORY_SEPARATOR
	. 'phpstan';
//$run_phpstan = file_exists($phpstan_path);

$phpUnitPath =
	'vendor'
	. DIRECTORY_SEPARATOR
	. 'bin'
	. DIRECTORY_SEPARATOR
	. 'phpunit';
//$runPhpUnit = file_exists($phpUnitPath);

foreach ($files as $file) {

	if (strtolower(pathinfo($file, PATHINFO_EXTENSION)) !== 'php') {
		
		continue;
	}

	exec(
		$nebsites_configuration->command
		. ' '
		. $phpstan_path
		. ' analyse '
		. escapeshellarg($file),
		$output,
		$return
	);
	
	$returns[] = $return;
// 
// 	$phpUnitClassPath =
// 		'tests'
// 		. DIRECTORY_SEPARATOR
// 		. pathinfo($file, PATHINFO_DIRNAME)
// 		. DIRECTORY_SEPARATOR
// 		. pathinfo($file, PATHINFO_FILENAME);
// 	
// 	if (
// 		$runPhpUnit
// 		&& file_exists($phpUnitClassPath)
// 	) {
// 		
// 		exec(
// 			$phpUnitPath
// 			. ' '
// 			. $phpUnitClassPath
// 			. DIRECTORY_SEPARATOR
// 			. '*',
// 			$output,
// 			$return
// 		);
// 
// 		$returns[] = $return;
// 	}
}

echo implode(PHP_EOL, $output);

exit((int) !empty(array_filter($returns)));
