#!/usr/bin/php
<?php

$replace = '    ';
$with = '	';

while (($line = fgets(STDIN)) !== false) {

	$content = ltrim($line);
	$indentation = str_replace($content, '', $line);
	
	echo
		rtrim(
			str_replace(
				$replace,
				$with,
				$indentation
			)
			. $content
		)
		. PHP_EOL;
}
